### ISSUE TITLE
Styles not being applied to .p-switch

### ISSUE THREAD

**Issue by barrymcgee** [vanilla-framework/vanilla-components#10]
## Replicate issue

- Clone this repo
- Run `npm start`
- View [http://localhost:3000](http://localhost:3000)
- See that buttons are styled but not the switch component

The version of Vanilla Framework being imported is 1.5.4 which includes the Switch component styling - as [verified on Codepen](https://codepen.io/barrymcgee/pen/boWQYR)

If you inspect the component, no styles seem to be applied to `.p-switch`

Any ideas @anthonydillon or @Lukewh?

**Comment by Lukewh** [comment]
On my phone but looks like should work, will check on Monday @barrymcgee

**Comment by anthonydillon** [comment]
Also seems ok here.

**Comment by barrymcgee** [comment]
This is what I see?

<img width="823" alt="screen shot 2017-10-09 at 12 49 38" src="https://user-images.githubusercontent.com/505570/31336838-98e0a0dc-acf0-11e7-83a2-2cde37034ad4.png">

**Comment by Lukewh** [comment]
Just had a look at this and seems the CSS is breaking at some point. `.p-strips` don't work either and they're defined just before the `.p-switch` @barrymcgee
