### ISSUE TITLE
Eslint throwing fatal error over variable declaration

### ISSUE THREAD

**Issue by barrymcgee** [vanilla-framework/vanilla-components#17]
Can't qyuite figure this out 

1. Pull code
2. Run `npm run lint`
3. The following "fatal" error is thrown:
<img width="474" alt="screen shot 2017-10-11 at 16 16 53" src="https://user-images.githubusercontent.com/505570/31449737-a12e9702-ae9f-11e7-8b28-711e7f14f6d3.png">
4 ..which points to this line → https://github.com/vanilla-framework/vanilla-components/blob/master/src/App.js#L10

Why is this not valid? 🤔

**Comment by anthonydillon** [comment]
No var, let, const?

**Comment by barrymcgee** [comment]
@anthonydillon No, doesn't make a difference but based on @Lukewh's [comment on the other PR](https://github.com/vanilla-framework/vanilla-components/pull/18#discussion_r144047386) I think I'm passing the object incorrectly which is why it's complaining...

**Comment by Lukewh** [comment]
Are you trying to create an instance variable? If so it'll need to be in a constructor:

```
constructor() {
  super();
  this.cardImg = {...};
}
```

My comment about passing an object I meant:

```
<Card img={{src: '', alt: ''}} />
```

That would allow (in the card component) to do `this.props.img.src` and `this.props.img.alt`. grouping the image API in to one object.

**Comment by barrymcgee** [comment]
@Lukewh Yes, that was it, needed a `constructor()` - thanks!
